
(defun C:DrawMyObject ()
  (command "_.UNDO" "Begin")
  (setvar "CMDECHO" 0)
  ;; --- 动态图层设置 ---
  (command "_.-LAYER" "_M" "Outline" "_C" "7" "" "")(if (not (tblsearch "LTYPE" "HIDDEN")) (command "_.-LINETYPE" "_L" "HIDDEN" "acad.lin" "" ""))(command "_.-LAYER" "_M" "Hidden" "_C" "7" "" "_L" "HIDDEN" "" "")(if (not (tblsearch "LTYPE" "CENTER")) (command "_.-LINETYPE" "_L" "CENTER" "acad.lin" "" ""))(command "_.-LAYER" "_M" "Centerline" "_C" "1" "" "_L" "CENTER" "" "")(command "_.-LAYER" "_M" "Dimensions" "_C" "2" "" "")(command "_.-LAYER" "_M" "Annotations" "_C" "6" "" "")(command "_.-LAYER" "_M" "Parameter_Table" "_C" "7" "" "")
  ;; --- 标注和系统变量设置 ---
  (setvar "LTSCALE" 5.0)
  (setvar "DIMTXT" 3.5)
  (setvar "DIMASZ" 2.5)
  (setvar "DIMCLRD" 2)
  (setvar "DIMCLRE" 2)
  (setvar "DIMCLRT" 2)
  (setvar "DIMDEC" 2)

;; =============================================================================
;; == 辅助标注函数定义 (由Python生成)
;; =============================================================================
(defun dtr (a) (* pi (/ a 180.0)))
(defun draw-roughness-symbol (ins_pt text_val sym_size rotation / p1 p2 p3 p4 ang1 ang2 text_height text_pt) (setq text_height (* sym_size 0.4)) (setq ang1 (dtr (+ rotation 60.0))) (setq ang2 (dtr (+ rotation 120.0))) (setq p1 ins_pt) (setq p2 (polar p1 ang1 sym_size)) (setq p3 (polar p2 ang2 sym_size)) (setq p4 (polar p3 (dtr rotation) (* sym_size 1.5))) (command "_.-LAYER" "_S" "Annotations" "") (command "_.PLINE" p1 p2 p3 "") (command "_.LINE" p3 p4 "") (setq text_pt (polar p2 (dtr (+ rotation 90)) (* text_height 0.4))) (command "_.TEXT" "_J" "_BL" text_pt text_height rotation text_val) )
(defun draw-datum-symbol (attach_pt label_pt label / frame_size p1 p2) (setq frame_size (* 3.5 2.0)) (command "_.-LAYER" "_S" "Annotations" "") (command "_.LEADER" attach_pt label_pt "" "" "_N") (setq p1 (list (- (car label_pt) (/ frame_size 2.0)) (- (cadr label_pt) (/ frame_size 2.0)))) (setq p2 (list (+ (car label_pt) (/ frame_size 2.0)) (+ (cadr label_pt) (/ frame_size 2.0)))) (command "_.RECTANG" p1 p2) (command "_.TEXT" "_J" "_MC" label_pt 3.5 0 (strcat "-" label "-")) )
(defun draw-gdt-frame (attach_pt frame_loc gdt_sym tolerance datums leader_side / total_width current_x box_w box_h leader_start_pt) (setq box_w (* 3.5 2.5)) (setq box_h (* 3.5 2.0)) (setq current_x (car frame_loc)) (setq total_width (+ box_w (* box_w 2) (* (if datums (length datums) 0) box_w))) (command "_.-LAYER" "_S" "Annotations" "") (if (or (not leader_side) (= (strcase leader_side) "LEFT")) (setq leader_start_pt (list (car frame_loc) (+ (cadr frame_loc) (/ box_h 2.0)))) (setq leader_start_pt (list (+ (car frame_loc) total_width) (+ (cadr frame_loc) (/ box_h 2.0))))) (command "_.LEADER" attach_pt leader_start_pt "" "" "_N") (command "_.RECTANG" (list current_x (cadr frame_loc)) (list (+ current_x box_w) (+ (cadr frame_loc) box_h))) (command "_.TEXT" "_J" "_MC" (list (+ current_x (/ box_w 2.0)) (+ (cadr frame_loc) (/ box_h 2.0))) 3.5 0 gdt_sym) (setq current_x (+ current_x box_w)) (command "_.RECTANG" (list current_x (cadr frame_loc)) (list (+ current_x (* box_w 2)) (+ (cadr frame_loc) box_h))) (command "_.TEXT" "_J" "_MC" (list (+ current_x box_w) (+ (cadr frame_loc) (/ box_h 2.0))) 3.5 0 tolerance) (setq current_x (+ current_x (* box_w 2))) (if datums (foreach datum datums (command "_.RECTANG" (list current_x (cadr frame_loc)) (list (+ current_x box_w) (+ (cadr frame_loc) box_h))) (command "_.TEXT" "_J" "_MC" (list (+ current_x (/ box_w 2.0)) (+ (cadr frame_loc) (/ box_h 2.0))) 3.5 0 datum) (setq current_x (+ current_x box_w)))) )
(defun Draw-Parameter-Table (start_pt title data_list col_widths row_height text_height / num_rows total_height total_width header_height current_y p1 p2 p3 p4 text_mid_y row_data i col_div_x) (command "_.-LAYER" "_S" "Parameter_Table" "") (setq num_rows (length data_list)) (if (> num_rows 0) (progn (setq header_height (* row_height 1.5)) (setq total_height (+ header_height (* num_rows row_height))) (setq total_width (apply '+ col_widths)) (setq p1 start_pt) (setq p2 (list (+ (car p1) total_width) (cadr p1))) (setq p3 (list (+ (car p1) total_width) (- (cadr p1) total_height))) (setq p4 (list (car p1) (- (cadr p1) total_height))) (command "_.RECTANG" p1 p3) (command "_.LINE" (list (car p1) (- (cadr p1) header_height)) (list (car p2) (- (cadr p2) header_height)) "") (setq col_div_x (+ (car p1) (car col_widths))) (command "_.LINE" (list col_div_x (- (cadr p1) header_height)) (list col_div_x (cadr p3)) "") (setq text_mid_y (- (cadr p1) (/ header_height 2.0))) (command "_.TEXT" "_J" "_MC" (list (+ (car p1) (/ total_width 2.0)) text_mid_y) (* text_height 1.2) 0 title) (setq current_y (- (cadr p1) header_height)) (setq i 0) (foreach row_data data_list (setq text_mid_y (- current_y (/ row_height 2.0))) (command "_.TEXT" "_J" "_MC" (list (+ (car p1) (/ (car col_widths) 2.0)) text_mid_y) text_height 0 (car row_data)) (command "_.TEXT" "_J" "_MC" (list (+ col_div_x (/ (cadr col_widths) 2.0)) text_mid_y) text_height 0 (cadr row_data)) (setq current_y (- current_y row_height)) (setq i (1+ i)) (if (< i num_rows) (command "_.LINE" (list (car p1) current_y) (list (car p2) current_y) ""))) (princ))))
(defun Draw-Bom-Table (start_pt title data_list col_widths row_height text_height / num_rows total_height total_width header_height current_y p1 p2 p3 p4 text_mid_y row_data i col_count current_x col_idx col_width temp_widths width) (command "_.-LAYER" "_S" "Parameter_Table" "" "") (setq num_rows (length data_list)) (setq col_count (length col_widths)) (if (> num_rows 0) (progn (setq header_height (* row_height 1.5)) (setq total_height (+ header_height (* num_rows row_height))) (setq total_width (apply '+ col_widths)) (setq p1 start_pt) (setq p2 (list (+ (car p1) total_width) (cadr p1))) (setq p3 (list (+ (car p1) total_width) (- (cadr p1) total_height))) (setq p4 (list (car p1) (- (cadr p1) total_height))) (command "_.RECTANG" p1 p3) (command "_.LINE" (list (car p1) (- (cadr p1) header_height)) (list (car p2) (- (cadr p2) header_height)) "") (setq current_x (car p1)) (setq temp_widths col_widths) (while (setq width (car temp_widths)) (setq current_x (+ current_x width)) (setq temp_widths (cdr temp_widths)) (if temp_widths (command "_.LINE" (list current_x (cadr p1)) (list current_x (cadr p3)) ""))) (setq text_mid_y (- (cadr p1) (/ header_height 2.0))) (command "_.TEXT" "_J" "_MC" (list (+ (car p1) (/ total_width 2.0)) text_mid_y) (* text_height 1.2) 0 title) (setq current_y (- (cadr p1) header_height)) (setq i 0) (foreach row_data data_list (setq text_mid_y (- current_y (/ row_height 2.0))) (setq current_x (car p1)) (setq col_idx 0) (foreach item row_data (setq col_width (nth col_idx col_widths)) (command "_.TEXT" "_J" "_MC" (list (+ current_x (/ col_width 2.0)) text_mid_y) text_height 0 (vl-princ-to-string item)) (setq current_x (+ current_x col_width)) (setq col_idx (1+ col_idx))) (setq current_y (- current_y row_height)) (setq i (1+ i)) (if (< i num_rows) (command "_.LINE" (list (car p1) current_y) (list (car p2) current_y) ""))) (princ))) )
(defun Draw-Balloon (center_pt radius text_val text_height) (command "_.-LAYER" "_S" "Annotations" "") (command "_.CIRCLE" center_pt radius) (command "_.TEXT" "_J" "_MC" center_pt text_height 0 text_val))

  ;; --- 绘制主视图 ---
  (command "_.-LAYER" "_S" "Outline" "")
  (command "_.LINE" (list 10.0 36.0) (list 20.0 36.0) "")
  (command "_.LINE" (list 10.0 36.0) (list 10.0 30.0) "")
  (command "_.LINE" (list 20.0 36.0) (list 20.0 30.0) "")
  (command "_.LINE" (list 10.0 30.0) (list 11.6 30.0) "")
  (command "_.LINE" (list 20.0 30.0) (list 18.4 30.0) "")
  (command "_.LINE" (list 12.0 11.0) (list 12.0 29.6) "")
  (command "_.LINE" (list 18.0 11.0) (list 18.0 29.6) "")
  (command "_.LINE" (list 12.0 11.0) (list 13.0 10) "")
  (command "_.LINE" (list 18.0 11.0) (list 17.0 10) "")
  (command "_.LINE" (list 13.0 10) (list 17.0 10) "")
  (command "_.ARC" "_C" (list 11.6 29.6) (list 12.0 29.6) (list 11.6 30.0))
  (command "_.ARC" "_C" (list 18.4 29.6) (list 18.4 30.0) (list 18.0 29.6))
  (command "_.LINE" (list 13.0 10) (list 13.0 28) "")
  (command "_.LINE" (list 17.0 10) (list 17.0 28) "")
  (command "_.LINE" (list 12.0 11.0) (list 18.0 11.0) "")
  (command "_.-LAYER" "_S" "Outline" "")
  (command "_.LINE" (list 12.0 30.0) (list 18.0 30.0) "")
  (command "_.LINE" (list 12.0 28) (list 18.0 28) "")
  (command "_.-LAYER" "_S" "Hidden" "")
  (command "_.LINE" (list 12.5 33.0) (list 15.0 31.556624327025936) "")
  (command "_.LINE" (list 15.0 31.556624327025936) (list 17.5 33.0) "")
  (command "_.LINE" (list 12.5 33.0) (list 12.5 36.0) "")
  (command "_.LINE" (list 12.5 36.0) (list 12.5 36.0) "")
  (command "_.LINE" (list 17.5 33.0) (list 17.5 36.0) "")
  (command "_.LINE" (list 17.5 36.0) (list 17.5 36.0) "")
  (command "_.LINE" (list 13.556624327025936 33.0) (list 13.556624327025936 35.38995766035927) "")
  (command "_.LINE" (list 16.443375672974064 33.0) (list 16.443375672974064 35.38995766035927) "")
  (command "_.LINE" (list 12.5 33.0) (list 17.5 33.0) "")

  ;; --- 绘制右视图 ---
  (command "_.-LAYER" "_S" "Outline" "")
  (command "_.LINE" (list 40.0 36.0) (list 50.0 36.0) "")
  (command "_.LINE" (list 40.0 36.0) (list 40.0 30.0) "")
  (command "_.LINE" (list 50.0 36.0) (list 50.0 30.0) "")
  (command "_.LINE" (list 40.0 30.0) (list 41.6 30.0) "")
  (command "_.LINE" (list 50.0 30.0) (list 48.4 30.0) "")
  (command "_.LINE" (list 42.0 11.0) (list 42.0 29.6) "")
  (command "_.LINE" (list 48.0 11.0) (list 48.0 29.6) "")
  (command "_.LINE" (list 42.0 11.0) (list 43.0 10) "")
  (command "_.LINE" (list 48.0 11.0) (list 47.0 10) "")
  (command "_.LINE" (list 43.0 10) (list 47.0 10) "")
  (command "_.ARC" "_C" (list 41.6 29.6) (list 42.0 29.6) (list 41.6 30.0))
  (command "_.ARC" "_C" (list 48.4 29.6) (list 48.4 30.0) (list 48.0 29.6))
  (command "_.LINE" (list 43.0 10) (list 43.0 28) "")
  (command "_.LINE" (list 47.0 10) (list 47.0 28) "")
  (command "_.LINE" (list 42.0 11.0) (list 48.0 11.0) "")
  (command "_.-LAYER" "_S" "Outline" "")
  (command "_.LINE" (list 42.0 30.0) (list 48.0 30.0) "")
  (command "_.LINE" (list 42.0 28) (list 48.0 28) "")
  (command "_.-LAYER" "_S" "Hidden" "")
  (command "_.LINE" (list 42.11324865405187 33.0) (list 45.0 31.333333333333332) "")
  (command "_.LINE" (list 45.0 31.333333333333332) (list 47.88675134594813 33.0) "")
  (command "_.LINE" (list 42.11324865405187 33.0) (list 42.11324865405187 36.0) "")
  (command "_.LINE" (list 42.11324865405187 36.0) (list 42.5 36.0) "")
  (command "_.LINE" (list 47.88675134594813 33.0) (list 47.88675134594813 36.0) "")
  (command "_.LINE" (list 47.88675134594813 36.0) (list 47.5 36.0) "")
  (command "_.LINE" (list 45.0 33.0) (list 45.0 36.0) "")
  (command "_.LINE" (list 42.11324865405187 33.0) (list 47.88675134594813 33.0) "")

  ;; --- 绘制俯视图 ---
  (command "_.-LAYER" "_S" "Outline" "")
  (command "_.CIRCLE" (list 15.0 61.0) 5.0)
  (command "_.POLYGON" 6 (list 15.0 61.0) "_I" 2.5)
  (command "_.CIRCLE" (list 15.0 61.0) 2.5)
  (command "_.ARC" "_C" (list 15.0 61.0) (polar (list 15.0 61.0) (dtr 135) 2.5) (polar (list 15.0 61.0) (dtr 45) 2.5))

  ;; --- 绘制中心线 ---
  (command "_.-LAYER" "_S" "Centerline" "")
  (command "_.LINE" (list 15.0 -10) (list 15.0 86.0) "")
  (command "_.LINE" (list 45.0 -10) (list 45.0 56.0) "")
  (command "_.LINE" (list -10.0 61.0) (list 40.0 61.0) "")
  (command "_.LINE" (list -10 20.0) (list 70.0 20.0) "")

  ;; --- 尺寸标注 ---
  (command "_.-LAYER" "_S" "Dimensions" "")
  (command "_.DIMLINEAR" (list 10.0 10) (list 10.0 36.0) (list -10.0 23.0))
  (command "_.DIMLINEAR" (list 20.0 30.0) (list 20.0 36.0) (list 30.0 33.0))
  (command "_.DIMDIAMETER" "" (list 12.879 20.0) (list -8.0 20.0))
  (command "_.DIMDIAMETER" "" (list 11.465 64.535) (list -10.0 86.0))
  (command "_.DIMLINEAR" (list 12.5 61.0) (list 17.5 61.0) (list 15.0 36.0))
  (command "_.DIMLINEAR" (list 18.0 10) (list 18.0 28) (list 38.0 19.0))

  ;; --- 高级标注 (示例) ---
  (draw-datum-symbol (list 20.0 30.0) (list 40.0 30.0) "A")

  ;; --- 绘制参数表 (调用原始的Draw-Parameter-Table) ---
  (setq table_start_pt (list 70.0 36.0))
  (setq param_data (list (list "Nominal Designation" "GB/T 70.1 M6x26") (list "Head Diameter" "10.0") (list "Head Height" "6.0") (list "Shaft Diameter" "6.0") (list "Shaft Length" "20.0") (list "Socket Depth" "3.0") (list "Socket Width Across Flats" "5.0") (list "Thread Pitch" "1.0") (list "Thread Depth" "0.5") (list "Fillet Radius" "0.4") (list "Chamfer Head Length" "0.5") (list "Chamfer End Length" "1.0") (list "Socket Countersink Diameter" "5.0") (list "Material" "Alloy Steel") (list "Finish" "Black Oxide") (list "Thread Length" "18") (list "End Chamfer Size" "1.0")))
  (Draw-Parameter-Table table_start_pt "Parameter List" param_data '(150 80) 15 3.5)

  (setvar "CMDECHO" 1)(command "_.ZOOM" "_E")(command "_.UNDO" "End")
  (princ "\nSocket Head Cap Screw drawing completed!\n")(princ))
(princ "\nLISP file loaded. Type 'DrawMyObject' to run.")(princ)